name: GitHub Snake Game

on:
  # Planifier l'exécution du workflow tous les jours à minuit UTC
  schedule:
    - cron: "0 0 * * *"

  # Permettre un déclenchement manuel du workflow
  workflow_dispatch:

  # Déclencher le workflow lors de pushs sur la branche principale
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Étape 1 : Récupérer le dépôt
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Étape 2 : Générer les animations de contributions Snake
      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          # Nom d'utilisateur GitHub pour générer l'animation
          github_user_name: ${{ github.repository_owner }}
          # Définir les fichiers de sortie et leurs configurations
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Étape 3 : Déployer les fichiers générés sur la branche 'output'
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          # Message de commit personnalisé
          commit_message: "Update snake animation [skip ci]"
